# -*- coding: utf-8 -*-
"""Write the 2026-08-29 research entry into the Harvest Log."""
import pathlib

p = pathlib.Path("Obsidian God-level Marketing Vault/God-level Marketing/wiki/science/Harvest Log.md")
t = p.read_text(encoding="utf-8")
anchor = "## 2026-08-29 (teacher run)"
assert anchor in t, "teacher anchor not found"

entry = """## 2026-08-29 (research run)

**0 new transcripts, 63 still unextracted, and the quiet day was nearly a false reading.** The daily harvest returned zero with **8 of 12 channels failing to list** on HTTP 404 and 500 from the YouTube RSS endpoint. The failures ROTATE between runs, which is the tell that they are rate limiting and not dead channel IDs: three cleared on a plain retry, the last four cleared with exponential backoff, and at that point **4 genuinely new videos appeared** from Mark Builds Brands and Dr. Matt Shiver. All four were Shorts and all four were correctly skipped under the 150-second floor. **So today really was quiet, but the first run could not have known that, and `lib/harvest.py` has no retry around `rss_ids`.** Any morning run can report zero while two thirds of the roster was never read. Logged as a watch item.

**Watchlist: 2 real findings out of 3 candidates, both read in full at source.**

**Meta is targeting 90% of its global ad revenue from VERIFIED advertisers by end-2026, against 70% in 2025 (MD-149, T1).** It surfaced in a Polish-language Newsroom post whose own rule is narrow, identity verification demanded from 100% of financial-services advertisers targeting Poland within weeks. Both figures were pulled verbatim rather than from a summary: *"weryfikacji bedziemy wymagac od 100% reklamodawcow uslug finansowych kierujacych reklamy do Polski"* and *"do konca 2026 roku 90% przychodow reklamowych Mety na swiecie pochodzilo od zweryfikowanych reklamodawcow, wobec 70% w 2025 roku."* **A 20-point shift in the share of revenue that must be identity-verified, inside sixteen months, is a change to who is allowed to buy inventory.** Nothing says our verticals face a check; the mechanism is category-plus-geography expansion, so the move is preparatory, not urgent. **The codex had ZERO coverage of advertiser verification before today.**

**Google's August Demand Gen drop carries a 30% figure that will be quoted at us (GA-068, T1).** Messaging-app conversations from Demand Gen ads on YouTube (a test, and the first Demand Gen surface that yields a conversation rather than a click), travel personalisation, and multimodal video in Asset Studio now generally available. The **"30% average increase in conversions or conversion value"** is labelled *"Google Internal Data, Global, H2 2025"*: a vendor aggregate over self-selected adopters, no control, no holdout. Against it we already hold a measured 21-day Demand Gen geo holdout with **no new-customer lift**, 85 orders against the 166 required (GA-055 / AT-072 / GP-040). **Both can be true. Only ours had a counterfactual.**

Third candidate read and discarded: Meta's closed-loop cooling post, data-centre infrastructure, no advertising content. arXiv cs.IR served **today's** build (Sat 29 Aug 04:00 UTC) rather than yesterday's, because this run fired at 12:02 IST instead of 07:00, and it was empty, which is the normal weekend result. TikTok SDK changelog unchanged at v0.1.8; the India geo-block still leaves TikTok policy and creative unmonitored. Google Ads announcements page diffed 1 line added and 1 removed at identical line counts, both bare numeric tracking IDs, so noise. Weekly Monday sources skipped, correctly, on a Saturday.

**Backlog pass: 15 transcripts read IN FULL and merged, 63 left, and the selection rule is stated because it deviates from a flat top-25.** With 78 unextracted the runbook's 25-most-substantive rule applied. Most of the backlog is off-topic for our book (mindset tier-lists, Shopify and Merchant Center tutorials), so the pick was the 2 newest core items plus the highest-density remainder, and the count was cut to 15 in order to merge every one of them properly rather than skim 25. **Nothing was flagged `extracted` that was not read start to finish.**

**12 new claims, 7 amendments, across 7 topic files. The codex stands at 1,097 claims (88 T1, 112 T2, 749 T3, 148 T4; 992 active, 99 contested, 5 superseded, 1 refuted).**

**The most important new claim is methodological and it undercuts our own testing habits (AT-107, T3, promoted to law 23).** Two ad sets duplicated with identical ads, audience, placements and budget still diverge: *"you will never have a duplicated ad set perform consistently with its adjacent ad set."* Across many duplicates *"some will perform terrible, some will perform incredible. It's just random."* **Nobody has published the spread, so the noise floor under every single-pair ad-set test in this codex is unmeasured.** The operator states it while killing his own finding: he ran 7-day click against 7-day-click-plus-1-day-view, measured the latter winning by **2-3x**, and refuses to bank it because he cannot separate the effect from the noise. **The 2-3x is recorded only so nobody re-extracts it later as a result.** He also supplies the method that does work, shown on a live account: three simultaneous changes halved conversion rate from **4% to 2%**, serial reversion cleared the offers and the restructure with no movement, and removing the checkout cross-sells snapped it straight back to 4%. **The cross-sells, the change credited with the +2% AOV win, were the thing destroying conversion rate.**

**Two dangling claim links from yesterday's interrupted merge are repaired, by reading their sources rather than by inventing the claims.** CR-200 now holds the reason home-market winners do not travel: brand presence, not market nuance, and the same operator measures it on his own agency at **double the cost per qualified booked call** in the US and UK. SC-151 now holds the per-PRODUCT spend ceiling that MD-137 had been pointing at, with the line that matters for us, that no volume of creative testing, angles or agency changes breaks it. **The codex now has zero dangling claim links.**

**New this pass, by file.** Meta Delivery: MD-149 (advertiser verification). Google Auction: GA-068 (Demand Gen drop). Attribution: AT-107 (ad-set noise, above), AT-108 (a multi-store retailer's new-customer count is wrong by construction until offline retail data is joined; geo-lift run around clusters of physical STORES reading both online revenue and in-store foot traffic). Creative: CR-199 (test in the BAD months, because in a good month roughly half your ads look like winners and the false winners poison the next iteration), CR-200, CR-201 (the lead-gen post-click ladder: message match, mobile form rendering, creative intent, form length, trust placement, segmented retargeting, and verify the leak on session recordings BEFORE rebuilding). Scaling: SC-151. Marketing Math: MM-184 (never allocate opex or the agency fee into a split first-time-customer P&L, with the worked case where doubling spend leaves new-customer profit contribution flat while adding ~$18,000/month of returning contribution), MM-185 (an agency is worth a **10 to 30% efficiency delta**, not a growth engine, argued by an agency owner against his own interest), MM-186 (shown recovery from LTGP:CAC 0.5 to 1.2 in two months, CAC down ~70% in three, on four changes of which cutting TikTok to zero moved total volume not at all), MM-187 (a business that cannot spend ~25% of revenue on marketing will not reach eight figures, and the accounts beating that maths are buying a halo from non-paid channels: **10 ROAS against 4 on near-identical ads**).

**Amended:** MM-007 (**precision problem**, the same operator states fashion day-365 gross-profit lift as 45% in one video and 55% in another, with day-90 replicating exactly at 15%; quote it as 45-55% from recall until a shown cohort curve settles it), MM-097 (the Q1 testing window now has three arguments from two operators behind it, no longer asserted alone), SC-044 (Theriot is a THIRD operator on the 3x kill multiple and the only one supplying a duration floor, 3 days, because *"it takes about 72 hours for Facebook to fully optimize"*, which stops an ad set being killed on a 2am spend spike), SC-019 (Theriot running three CBOs split by product category at $54,000/7 days, plus per-country CBOs for a geo test that failed), CR-118 (a fourth hit-rate figure, **one in seven ads works and scales**, and the same operator refusing to state a product-launch hit rate because he has no data for it), AT-066 (Jon Loomer independently reaching Faris's "Meta is broken is almost never the diagnosis" and adding the ordered checklist Faris never gives: read the breakdowns by time, demographics, platform, placement and location BEFORE forming a theory), LS-025 (the client-owns-the-Business-Manager, agency-added-as-PARTNER structure stated explicitly, with account bans named as the risk).

**Gaps noticed.** Nobody has published a duplicated-ad-set outcome distribution, which is the single measurement that would let us size the noise floor under law 23. Nobody has a product-launch hit rate. The 45-vs-55% fashion retention split is one operator contradicting himself and we quote that band. And `harvest.py` needs a listing retry before any future zero-transcript day is trusted.

"""

p.write_text(t.replace(anchor, entry + anchor, 1), encoding="utf-8")
print("harvest log entry written")
