# -*- coding: utf-8 -*-
"""2026-09-14 Harvest Log entry. Prepends under the file's intro line."""
from pathlib import Path

LOG = Path(r"E:\claude code marketing skill\Obsidian God-level Marketing Vault\God-level Marketing\wiki\science\Harvest Log.md")

ANCHOR = "One line per Research run: what came in, what changed. Quiet days get one line and nothing else.\n"

ENTRY = """
## 2026-09-14 (research run)

**⚠ Meta rewrote a section of the Advertising Standards and is rolling it out by locale, so two people reading the same policy page today see different rules.** The section that was "Fraud, Scams, and Deceptive Practices" is now **"Prohibited Commercial Practices"** on the default locale, with its two policies collapsed into one pointer at a Community Standard. `/en-gb/` still shows the old name and both old policies. Verified in one browser session on both URLs: 32,611 characters against 33,672. **Never quote a Meta policy section name without saying which locale you read it on.** Banked MD-156, T1.

**3 transcripts in, all read in full** (Blue Sense Digital 10,571w on Alo Yoga, Sam Piliero 4,007w, Fraser Cottrell 4,054w). **18 claims banked, 2 amended, 1 contested. Backlog 0.** Codex 1,192 to 1,211.

- New at T1: **MD-156** (the policy rename and locale split), **CR-234** (Pinterest's PinDCO gives each creative component its own scoring tower and adjusts for rendered size, +3.09% CTR), **LS-078** (ChronicleRec: ad ranking moving to cached, target-independent whole-history user summaries).
- New at T3, Alo Yoga: **SC-157** an account can be a harvesting layer with the top of funnel bought outside it, 96% of ads in the bottom two awareness stages, and the operator's estimate that an in-account change is worth about 1%. **CR-235** 5-day median live-ad age, 24-day oldest, and his verdict that a turnover clock this tight stops winners being milked. **CR-236** 0% of ads mention price, discount, risk reversal, loyalty or stores. **CR-237** a collection page makes the top six products the real landing page, and a size-curve stock-out tanks conversion with no account change. **CR-238** the creator-specific landing page. **MM-213** opening stores lifts that market's online revenue about 20% overnight, which confounds any blended read across the window.
- New at T3, Sam Piliero: **MM-214** break-even ROAS is one over gross margin, 1.49 at 33% COGS, 1.75 with a 10% take, **and his own sentence calling that "a 33% margin business" is wrong by 2x**. **MM-215** evergreen offers add value rather than subtract price, and the claimed cost of discounting instead is a degraded pixel. **AT-119** read the incremental-attribution column before a budget increase and treat it as the expectation for the next dollar: 16.04 against 8.53 shown on screen. **SC-158**, contested, interest ad sets run to widen the pixel rather than to scale, with interests chosen to be deliberately unlike the brand.
- New at T3, Fraser Cottrell: **CR-239** a static gets a glance, carries three parts, and its audience already knows the brand. **CR-240** a real on-site review reframed as a social comment, six figures spent, 3rd of 435 ads. **CR-241** the native storytelling static, where the caption carries the argument. **CR-242** the story-styled phone photo whose underlined @handle harvests mis-taps, 3.5% CTR reported. **CR-243** reviews as the source of both angle and voice, and porting a winning static's idea into other formats.
- Amended: **SC-024** gains the enforcement mechanism and, after five videos, the first stated reason: a 7-day minimum budget on every new pack, because "when we launch new ads in existing campaigns, they get no spend". **CR-031** gains the static-to-static threshold: vary the DESIGN and hold the MESSAGE, because a headline swap on one design does not read as a different asset.
- **SC-158 is contested against SC-070 and AT-061, and the shape of the disagreement is the interesting part.** Piliero concedes the conversions twice, unprompted. His claim is about CPM and reach. So the live proposition is new: an ad set can be worth running while contributing no incremental conversions, if what it changes is what the delivery system learns. Nothing first-party supports that, and the test is cheap.
- **CR-237 is independent convergence on GP-017 from a different channel and a different operator.** GP-017 has fashion size curves costing roughly 50% of Shopping efficiency; CR-237 has the same failure on a Meta-driven collection page. Two surfaces, two operators, reached separately.
- **Watchlist: 0 new on every readable source except arXiv.** Monday, so the 9 weekly sources were due and all were read. Marketing API index under-rendered to v25.0 for the fourth time, which is the known artefact; Graph API confirms v26.0 (29 Jul), unchanged. Google Ads API v25.1 (19 Aug) unchanged. Merchant Center newest still 11 Aug. AI at Meta carries no ads-ranking posts. Google Ads Developer Blog had one unbanked item, a 10 Sep post on API onboarding and the sunsetting of developer tokens, read in full and discarded as developer tooling with no ad-science content. Google Ads Announcements 2,350 lines against 2,350 cached, the added and removed IDs both render nonces for the third straight day.
- **arXiv returned a full Monday build (23 new, lastBuildDate 04:00:24 UTC, run at 05:20 UTC), which is the corrected rule from 2026-09-07 working as written.** 2 passed the ad filter, both read, both banked. ChronicleRec is a borderline pass and is labelled as one on the claim: "advertising" appears once, in the first sentence, which is the shape of all three recorded false positives. It was banked on the evaluation running on Tencent AdLive with a seven-day online A/B, not on the framing sentence.
- **TikTok is NOT logged as clean.** Only the SDK changelog was read, unchanged at 0.1.8. The Newsroom and the for-Business blog stay India geo-blocked.
- **Two watchlist methods fixed, both written into Watchlist.md.** Meta for Business News card dates drift by ONE DAY between runs (5 of 12 cards moved back a day today with the titles unchanged), so the date-diff rule adopted on 2026-08-20 is not safe on its own; diff on the TITLE and read the date only to decide whether to open a new one. **This also retires yesterday's reading that the card had "caught up" to the post byline. It drifted, and it drifted back.** Second, the Advertising Standards source-quality gap open since 2026-08-24 is CLOSED: the heading baseline caught its first real change today, and a per-section SHA-256 map of the body now exists, so a silent rewrite under an unchanged title is detectable from tomorrow.
- **⚠ The concurrency hazard carried since 2026-09-10 fired today, and it was survived by one ID number.** Both lanes launched at 10:42:37. The teacher lane wrote **MD-155** and Lesson 026 at about 10:54. This pass took its baseline count at 10:51, when MD-155 did not exist, and read the highest existing ID a few minutes later, when it did, so it correctly took MD-156. **Three minutes the other way and both passes write MD-155.** The fix is unchanged and still unbuilt: one lane, or an ID lock, or a stagger.
- **Good news on the same item: the teacher lane ran today.** Yesterday the watchdog relaunched only the research lane and left the teacher lane dead with no lesson. Today both launched and both completed.
- **No law added, none retired.** A reading rule was added for MD-156, and the CBO-starvation watch item gained a second route: Piliero's 7-day ad-set minimum, which needs no hidden control and is the one we could copy this week. The other two T1s are other platforms' internal architecture with no consequence for our book this week.
- **Claim count corrected against the published figure.** Yesterday's log published 1,191 and the team sync printed 1,192, with the difference attributed to a Harvest Log heading the sync counter mistakes for a claim. **That attribution was wrong for at least part of the gap**: the 2026-09-13 teacher pass banked MM-212 after yesterday's count was taken, so the codex genuinely held 1,192 by the evening. Today: 1,192 plus MD-155 from the teacher lane plus 18 from this pass = **1,211**, verified by the scoped counter with both columns summing.
- Gaps still open: GeoX still not installed, eighth consecutive naming. Qualified Future Conversions still has no codex entry, carried since 3 September. The arXiv framing-sentence filter still has no co-occurrence rule, and it produced a borderline pass today that had to be adjudicated by hand. The launcher still cannot tell an auth failure from a quiet day. YouTube RSS remains dead for 11 of 12 channels, with the /videos-tab fallback the only listing route.
"""

t = LOG.read_text(encoding="utf-8")
assert t.count(ANCHOR) == 1, f"anchor count {t.count(ANCHOR)}"
LOG.write_text(t.replace(ANCHOR, ANCHOR + ENTRY, 1), encoding="utf-8")
print("Harvest Log entry written")
