# -*- coding: utf-8 -*-
"""Prepend the 2026-09-08 research entry to the Harvest Log."""
from pathlib import Path

S = Path(r"E:\claude code marketing skill\Obsidian God-level Marketing Vault"
         r"\God-level Marketing\wiki\science")
LOG = S / "Harvest Log.md"

ENTRY = """## 2026-09-08 (research run)

**2 new transcripts, both read in full, both worth banking. 4 claims added, 6 amended, 0 errors on every readable source.** Harvest listed all 12 channels clean, 8 videos skipped under the length floor, 1 with no subtitles. Backlog was 0 going in and is 0 going out. **No law changed:** everything banked today is T3 from a single operator with nothing shown, so the law layer was left alone.

**Andrew Faris supplied the mechanism for why a manual bid breaks at a sale, and it breaks in BOTH directions from one cause (AU-086, T3, new).** Meta builds the bid's prediction from spend, predicted clicks and predicted purchases, and refuses to reprice off a small sample; five clicks that all convert do not produce a 100% conversion-rate forecast. **That refusal to overreact is the whole value of a manual bid in a normal week and it is exactly what fails at a promotion**, because a discount lifts conversion rate as a step change while the prediction still sits on full-price behaviour. At the start of a sale Meta underdelivers: his case is a Friday-to-Monday sale returning 20 purchases at $50 against 8 the day before at $100, on an ad set aimed at 2:1, landing near 3:1 with the volume you cut price to buy left unbought. At the end of a sale the prediction has learned the sale-era conversion rate and keeps spending against it into full-price traffic at something like $150 against a $100 target. **Why watching harder does not fix it:** Meta never exposes how far through the update it is or what conversion rate it currently expects, and the reported return column lags because conversions land late. His committed remedy is the back end, pre-committed and automated because it fires at midnight: drop budget AND bid together the day the sale ends, a $100 target to a $50 cap, $10,000 of expected good spend to $7,000.

**His most useful move is a configuration swap, and he retracts the tactic he is widely quoted for (AU-087, T3, new).** Normal manual-bid practice puts the budget far above real spend so the bid does all the pacing, $5,000/day behind a $50,000 to $100,000 budget. **At the opening of a sale that is the most dangerous configuration available, because the bid is loosened at the moment delivery is least predictable.** His move reverses the roles: raise the cap and pull the budget DOWN to a number he can confidently spend well, so the budget becomes the safety pacer while the bid pushes. Worked shape: $10,000/day behind a $100,000 to $200,000 budget goes to a $40,000 budget with a more aggressive cap, then flips back once delivery lands at target. **The retraction:** he describes pushing a $100 cap to $150 to force spend, then says "I generally am at a point now where I think it's not the best idea to do this", because Meta catches up faster than the operator notices and spends past the true target. This is the general fix for the risk already on file from the other direction, since [[Auction Mechanics & Bidding#AU-026|AU-026]] has Charley T naming a high budget ceiling behind a low bid as what leaks thousands when a cap breaks. His own gap, stated: "There is probably a mathy way to do this. I just haven't really found it yet."

**A short sale is a reason to auto-bid it (AU-088, T3, new), and the axis is new to this topic.** A manual bid earns its place by not adjusting quickly, so inside a two-to-four-day window it cannot adjust at all and just holds a stale full-price prediction. Manual bids when purchase density is high, "hundreds of purchases per day, even at a low spend"; auto bids when the sale is short or conversions are few. **Every threshold at [[Auction Mechanics & Bidding#AU-012|AU-012]] is monthly account spend; this one is conversion density and window length, and he decouples it from spend explicitly.** For our client sizes both readings agree, so a short promotion on any account we run should be auto-bid. Build attached: pre-schedule a separate sale campaign with ads approved before it opens, on its own budget and bid.

**Two Faris amendments, and one of them narrows a claim we could have quoted wrongly.** [[Auction Mechanics & Bidding#AU-028|AU-028]] says Meta widens reach on its own under a bid cap so a seasonal account needs no intervention. **The account behind it is a gift brand rising over ~30 days with NO price change**, and today the same speaker describes needing intervention for a discounted promotion where the lag costs volume inside a weekend. Compatible on the facts, since only window length and price discontinuity differ, and a catch-up arriving on its own is worth nothing inside a four-day sale. **He never reconciles them.** Left active with the scope stated rather than flipped to contested, because the two describe different situations. [[Auction Mechanics & Bidding#AU-029|AU-029]] was carrying half a calculation: a promotion moves MARGIN underneath the AOV at the same time, so the cap tracks AOV and the target tracks margin, with one real exception, that shipping and pick-and-pack are close to fixed per order so a second unit adds $1 to $2 against $10 for the first. He closes the general case with a number: at 40% off, fulfilment savings do not come close to covering it.

**Nick Theriot supplied the rule for CHOOSING a format once the message is settled (CR-230, T3, new).** [[Creative Science#CR-125|CR-125]] already settles that format is tested last; this is how you pick it. Two questions: what has to be communicated, and what carries the proof. UGC when the product must be seen, "people believe what they see, not what they hear", at $200 to $300 per creator plus shipping and turnaround. Static when there is one quick message. Native when the job is storytelling. **The destination is the boundary and it is what makes the rule usable:** his acne client's static only names a new mechanism because the ad drives to a booked call and the call sells, while the same offer pointed at a sales page "would need a longer sales letter". The same product, market and message change format when the funnel changes, so a format decision copied between two accounts with different funnels is copied wrong.

**The native format finally got its cost, and it lands on the promotional peak ([[Creative Science#CR-047|CR-047]] amended).** The claim listed only benefits, credibility and page-cap relief. Theriot runs natives under an invented person's name and states the price: "you don't build any brand value... if you ever decide to do like a sales promo or like a new product drop, it doesn't do as hot." **Cheap acquisition now is paid for with a weaker peak later**, which is the trade an account running natives as its main format is actually making. His demographic read: case studies cluster at 35 or 40 plus, few wins seen at 18 to 30.

**Three more creative amendments.** [[Creative Science#CR-048|CR-048]] gains a real before-and-after with both of its problems attached: an all-static account at $491 cost per purchase moved to UGC video and reported roughly $119 in the first 30 days, stated as a 75% drop. **He says "$107" earlier and "$119" later in the same passage, and only $119 fits his own 75%, so quote $119.** And it is an agency TAKEOVER, so structure, bidding, targeting, budget and copy all changed alongside the format; it is a real account and it is not evidence that format alone moved the cost. [[Creative Science#CR-117|CR-117]] gains a third operator in the right tail: a single static created 2025-07-19 had spent **$260,000 by 2026-09-03**, roughly 170 to 370 times this claim's $700 to $1,500 mean. [[Creative Science#CR-125|CR-125]] gains a fifth operator and its first account observation, a group of ads carrying over $100,000 of combined spend on the SAME core messaging across several UGC videos plus an animated one. Closest thing on file to the natural experiment that claim wants, and still a spend screenshot with no cost per acquisition and no failed formats shown.

**⚠ Research-lane finding: arXiv came back empty on a TUESDAY, three hours after its own rebuild, and Watchlist.md's corrected rule does not predict it.** Read at 07:10 UTC: 892 bytes, HTTP 200, zero `<item>` elements, `lastBuildDate` Tue, 08 Sep 2026 04:00:17 +0000. **Not a fault, and documented on arXiv's own page.** `info.arxiv.org/help/availability.html` lists **Monday 2026-09-07 in its 2026 Holidays table**, and its schedule announces the Friday-14:00-to-Monday-14:00 window at **Monday 20:00 ET**, mailed Tuesday morning. The holiday deferred that mailing, so Tuesday's build carried nothing. It also explains why yesterday's Monday run was full at 27 items: that build carried the **Sunday 20:00 ET** announcement, untouched by the holiday. **Nothing was lost. The rule to add: check arXiv's published holiday list before calling an empty weekday build anything, and expect the empty day the day AFTER the holiday rather than on it.**

**Codex count was 2 low and is corrected.** Recomputed from the topic files: **1,175 claims (93 T1, 118 T2, 808 T3, 156 T4; 1,069 active, 100 contested, 5 superseded, 1 refuted).** The skill carried 1,169. Today added exactly 4, all T3 active, and **the T3 and T4 columns reconcile exactly** (804 + 4 = 808), so the drift is 1 T1 and 1 T2 missed by the previous recount, neither banked today. Method note: count on `^### [A-Z]{2}-\\d+` and read tier and status off the next line. Requiring `Status:` in a fixed position under-counts by 25, and requiring the ID to end in a digit collapses **MD-019b** into MD-019 and reports a false duplicate.

**Watchlist, 0 errors.** Meta Engineering 9 items 0 new, Meta Newsroom 10 items 0 new, Google Ads & Commerce 20 items 0 new, TikTok SDK changelog steady at v0.1.8. Google Ads Announcements: 2,350 visible lines against 2,350 cached, and the only diff was **1 bare 20-digit number added and 1 removed**, which is a per-request nonce rather than content. Monday-only sources not due on a Tuesday.

**Gaps.** The `playwright` browser timed out at 30s this session along with `playwright-arcads` and `playwright-higgsfield`, so the TikTok browser lane was skipped, per the runbook. **TikTok stays a genuine blind spot**, since only the SDK changelog answers and it ships endpoint names rather than policy or creative news; not logged as clean. Meta Advertising Standards still has no cached baseline, open since 2026-08-24. **And Faris's own open question is a live research target:** nobody has arithmetic for how far to move a cap against a known conversion-rate step change, because the operator cannot see where Meta is in its update. Any promotion on our own accounts could produce the first shown before-and-after.

"""

t = LOG.read_text(encoding="utf-8")
anchor = "## 2026-09-07 (research run)"
assert t.count(anchor) == 1, "anchor count %d" % t.count(anchor)
LOG.write_text(t.replace(anchor, ENTRY + anchor, 1), encoding="utf-8")
print("Harvest Log entry prepended")
