# -*- coding: utf-8 -*-
"""2026-08-31 research pass: append new claims to the codex topic files."""
from pathlib import Path

S = Path(r"E:\claude code marketing skill\Obsidian God-level Marketing Vault\God-level Marketing\wiki\science")

CLAIMS = {}

CLAIMS["Google Auction & Smart Bidding.md"] = """
### GA-069 \u00b7 Google is REMOVING campaign-level language targeting from Search and from the Search half of Performance Max in September 2026, and the language of your ad becomes the matching signal
Tier: T1, off Google's own help documentation \u00b7 Status: active
The most operationally significant platform item found in a month, and it lands next month.
**Google's help page states it plainly:** "Starting in September 2026, the way language targeting works is changing for Search campaigns and the Search Network portion of Performance Max campaigns." For Search: **"The campaign-level language targeting setting will be removed. Search ads will automatically match based on the language of your ads."** Google adds that no advertiser action is required.
**Scope, stated precisely, because the halves differ.** Search campaigns and AI Max for Search lose the setting outright. Performance Max keeps its campaign-level language setting for YouTube, Display, Discover and Gmail, and loses it **only for the Search Network portion**. So a single PMax campaign will run one channel on the ad's language and the rest on the old control.
**Existing criteria are not deleted, they stop working.** Language criteria already on a campaign can stay and simply no longer affect targeting.
**Why this belongs beside law 1a rather than in a settings changelog.** Language was a CONTROL on Google, in the sense law 1a uses the word: a hard boundary the platform would not cross, of the same family as location. Google is converting it into an inference drawn from the creative plus signals about what the user understands. **That is the Google-side instance of "creative is the targeting", arriving as an announced product change rather than as a thing operators noticed.** It is the second cross-platform parallel found in a month, after Optimized Targeting at [[Google Auction & Smart Bidding#GA-066|GA-066]], and it is stronger than GA-066 because this one is documented and dated. Read it beside [[Google PMax & Shopping#GP-042|GP-042]], which found the same pattern on the PMax new-customer toggle.
**What it means for a language-split account, and this is where to be careful.** Reporting on the change says Google's position is that accounts separating English, Spanish or other languages into their own campaigns can keep that structure, because the creative and the landing page carry the matching signal instead. **That reads as reassurance and it is a real loss of control: the campaign no longer bounds who sees which language, so the ad copy and the destination page are now the only things doing that job.** Any account of ours built to keep Spanish creative in front of Spanish speakers has to have that guaranteed by the creative from September, not by the setting.
**One detail read on a secondary source and NOT confirmed on Google's own page:** that adding or updating language criteria on a Search campaign will return `ContextError.OPERATION_NOT_PERMITTED_FOR_CONTEXT` through the API. Treat that as reported, not verified, until it is read on Google's developer documentation.
**Read quality, stated honestly.** The Google Ads Developer Blog carries the announcement post, dated 13 August 2026 and tagged `google_ads_api` and `google_ads_scripts`, but its body did not render to two separate fetches, so the title and date come from the blog index and the substance comes from the help centre page plus trade coverage. The help-centre quotations above were read directly.
Sources: Google Ads Help, About language targeting (answer 1722078), read 2026-08-31; Google Ads Developer Blog index entry "Google Ads language targeting changes starting September 2026", 2026-08-13; Search Engine Land, Google Ads is removing language targeting from Search campaigns, August 2026
Last touched: 2026-08-31
"""

CLAIMS["Google PMax & Shopping.md"] = """
### GP-043 \u00b7 Merchant Center performance reporting definitions changed on 24 August 2026, so any Shopping report spanning that date contains a definitional break
Tier: T1, off the Merchant Center changelog \u00b7 Status: active
Announced 11 August 2026, effective **24 August 2026**, which is seven days before this entry was written.
Google is modifying Merchant Center performance reports to align reporting definitions across Google surfaces including Ads and YouTube. The named specific is that **YouTube affiliate results are separated out from other metrics**.
**Why it is banked despite being small.** This is the same shape as the Meta 7-day-click redefinition already recorded in this codex: a metric changes meaning on a date, the number moves, and the movement gets read as performance. **A Shopping or Merchant Center number that steps on or around 24 August 2026 is a candidate definitional artefact and must be checked against the change before it is explained as a result.**
**Read quality.** The changelog entry was read; the linked detail page returned HTTP 404 to a direct fetch, so the exact metric-by-metric mapping has not been read and is not stated here. Do not describe the change more precisely than this entry does until that page is read.
Sources: Google Merchant Center announcements changelog, entry dated 2026-08-11, read 2026-08-31
Last touched: 2026-08-31
"""

CLAIMS["Creative Science.md"] = """
### CR-209 \u00b7 The Ads Library now stamps creative with a "protected" watermark, which breaks the copy-the-competitor-ad-into-AI workflow, and the same source misreads the impressions sort this codex already corrected
Tier: T3 \u00b7 Status: active
A change to the instrument at [[Creative Science#CR-190|CR-190]], reported four months after CR-190 was banked, and it cuts the other way.
Sam Piliero, 2026-08-31, walking the SKIMS and Honey Love libraries: "everything says protected. See, if we zoom in on any of these ads, it has the clear protected." The consequence he reports is a tooling one: **"Claude and ChatGPT will often see this ad and not do anything with it because it clearly has the protected watermark. So, the actual use of Facebook Ad Library has declined a little bit in just the last few weeks."**
**Scope and tier guard.** No screenshot of a refusal, no model named beyond two, no date for the rollout beyond "the last few weeks", and the speaker sells a paid tool that solves exactly this problem in the same video, so he has an interest in the Library being harder to use. **T3, and the commercial interest is part of the entry.** What is checkable for free and should be checked before anyone plans around it: open the Library on one of our own competitor sets and look at whether the watermark is present.
**Direct relevance to our own book.** We run a competitor swipe file built from Library pulls. If the watermark is real and persistent, the read-and-summarise half of that work is unaffected and the recreate-this-image half is the part that degrades.
**A misread by the same source, recorded because this codex already holds the correction.** He instructs sorting "by impressions from high to low" and says this "would show me across their 710 active ads, which ads have been active the longest". **Impressions and runtime are two different signals and the sort orders one of them.** [[Creative Science#CR-190|CR-190]] states the repaired heuristic explicitly: it is the INTERSECTION, "lots of impressions plus been running for a long time", because zombie ads sit active on zero spend. Anyone reading Piliero alone would take an impressions ranking as a longevity ranking. Do not.
**One number recomputed and it holds.** He states an account at 2.36 return on ad spend on $670,000 of spend and calls the revenue "like a million and a half". 670,000 x 2.36 = $1,581,200, so his rounding understates by 5.4% and passes. The vendor figure in the same video, 924,000 ads analysed, is a marketing claim with nothing behind it and is not banked.
Sources: Sam Piliero, Claude + Meta Ads Library = Unlimited Winning Ad Creatives, 2026-08-31
Last touched: 2026-08-31

### CR-210 \u00b7 Seven product-page tests with real numbers attached, the first CRO set on this roster to publish denominators, and the flagship shipping claim is contradicted by its own readout
Tier: T2 for the five measured tests, T3 for the win rates, T4 for the two with no number \u00b7 Status: active
Dave Diederen of Centra Labs, walking his Intelligems dashboards on camera with Andrew Faris, 2026-08-31. **This is the first source in this codex to state visitor counts and order counts test by test, which is why it gets a long entry and why it also gets [[Attribution & Incrementality#AT-111|AT-111]] sitting on top of it.**
**The five tests that published a sample size.**
1. **Bestseller badge above the product title**, paired with a second badge naming the buyer ("number one choice for clinicians"), placed above the review counter rather than on the product image. 140,000 visitors, roughly 3,500 orders, **conversion rate +6%**, revenue and revenue per visitor up, no profit figure because the brand had not connected its cost data. Claimed win rate 90 to 95%.
2. **Shipping information directly below the add-to-cart button**, as "ships by [date]" plus localised "fast US shipping" or "free US shipping" with the visitor's own country flag. Never "delivered by", because delivery has factors you do not control. **Conversion rate +11%, revenue per visitor +13%, profit per visitor +12.5%**, small lift in average order value. **Sample size not stated**, and Faris calls it "a smaller sample size" on screen. Claimed win rate 85 to 90%.
3. **Font size increased by two to four pixels for an older audience.** 57,000 visitors, 1,600 orders, **conversion rate +5%, revenue per visitor +6.5%**. Claimed win rate 85% plus. **Quote guard: Faris summarises this on air as a result "just by making the font 5% bigger". Diederen said two to four PIXELS. The 5% is the conversion lift, not the font change, and the two got fused in the recap.**
4. **Shipping price increased** on a brand already charging $2 to $3, in $0.50 and $1.00 increments. 250,000 visitors, 6,600 orders, **conversion rate +3.3%, revenue per visitor +4.7%**, slight lift in average order value. Multi-cell, at least three arms.
5. **Savings percentage written into the add-to-cart button** ("Add to cart - save 50%"), updating dynamically with the variant or bundle. 72,000 visitors, 1,300 orders, average order value about $66, **conversion rate +8.5%, revenue per visitor +13%, profit per visitor +13%, average order value +4%**. Claimed win rate 90%.
6. **Product title rewritten to lead with the benefit** and name the product second ("Feel safer going outside at night with Birdie 3.0"), deliberately long, up to ten words. 49,000 visitors, 1,900 orders, average order value about $45, **conversion rate +10%, revenue per visitor 12 to 13%, average order value +2%**.
**The two with NO number, banked as guards.** Test seven was **swapping the models on the page from people in their 20s and 30s to people in their 50s and 60s** for a brand with an older audience. He describes it as a repeat winner and reports **no figure at all**, calling it a smaller brand with less traffic. Separately, a **cart price breakdown** showing what you should have paid, what you are saving and what you are paying now, sourced from a client actually phoning their customers, is explicitly unmeasured: "I don't have like any accurate data because we're running active tests... for two three weeks on like five different brands but like the early signs are looking really good." **Per the precedent at [[Creative Science#CR-183|CR-183]]: any future note that assigns a percentage to either of these invented it.**
**\u26a0 The flagship claim is contradicted by its own test, inside two minutes of tape.** Diederen's headline on shipping price is "the higher the shipping price, the higher the conversion rate, the higher the revenue. Like that's what I've seen over and over again." The dashboard Faris reads out says conversion rate **+3.3%**. Then Diederen, describing the same result: **"yes CVR is down with the two more expensive like groups, revenue went up"**, and attributes the revenue gain to average order value. **Those cannot all be true.** The reading that fits the most testimony is that the top cells lost conversion rate and won on revenue, which makes this a revenue-per-visitor win and **not** evidence that a higher shipping price raises conversion. **Never repeat the headline. The defensible claim is that raising shipping price on a brand already charging for shipping did not cost revenue and probably raised margin.**
**Internal arithmetic, recomputed on all five, and every one holds.** Conversion lift times average-order-value lift reproduces the stated revenue per visitor: test 5 gives +12.84% against 13% stated, test 6 gives +12.2% against "12 almost 13%", and tests 2, 3 and 4 imply average order value moves of +1.80%, +1.43% and +1.36% against unquantified "small" and "slight" descriptions. **So the figures are coherently reported. The problem with this set is power, not honesty, and that is [[Attribution & Incrementality#AT-111|AT-111]].**
**Structural caveats that travel with every number above.** Intelligems is the episode's sponsor and is the tool producing every dashboard shown. Diederen sells the CRO service and chose which of his own tests to screen-share, so the set is selected, not sampled. **Every win rate quoted, 90 to 95%, 85 to 90%, 85% plus and 90%, is stated with no denominator: he never says across how many tests or how many brands.** Two of the six dashboards showed no profit figure because the brands had not connected cost data.
**The method note that makes the power problem worse rather than better,** and it is stated as advice: "if the first test fails, try another incrementation. Like try to go higher. Try to go like in like smaller increments. Like don't just stop when something doesn't work out." **That is running increments until one wins, which inflates the false-positive rate on top of samples that are already too small.**
**What is worth acting on anyway.** The changes are close to free, several are message-congruence moves rather than design moves, and they point the page at the same buyer the ad named, which is the same argument the landing-page family in this file already makes. **Treat them as sensible defaults to ship, not as measured lifts to forecast from.**
Sources: Andrew Faris with Dave Diederen (Centra Labs), 7 Real CRO Tests That Drove Big Profit Lifts, 2026-08-31
Last touched: 2026-08-31

### CR-211 \u00b7 Fraser Cottrell disclaims media-buying expertise in the same breath as prescribing a budget split, so his structural claims and his creative claims do not carry the same weight
Tier: T3 \u00b7 Status: active
A source-reliability entry of the same kind as [[Marketing Math & Unit Economics#MM-176|MM-176]], and a gentler one, because the operator volunteers the limit himself.
Cottrell, 2026-08-30, states his scale as "over 10,000 ads, tracked over 450 million in ad spend". He then gives a campaign-structure prescription: a testing campaign at 5 to 10% of budget holding different concepts, an Advantage+ scale campaign at 70 to 80% carrying only proven winners and reusing the same post ID to retain social proof, and a retargeting campaign at 10 to 15% which he says is "not that important anymore" because Meta does the work. **Immediately after giving it he says: "I'm not a media buyer by any means. There are some incredible people on YouTube that are going to teach you a much better way to test your creative, but that's just my two cents."**
**The operating rule that follows.** His creative and customer-research material sits inside his stated competence and is sourced from real production volume. **His campaign-structure and budget-split material is disclaimed by him on the record and should never be cited in this codex as a structural authority.** Where his split agrees with an operator who does buy media, cite that operator instead.
**Arithmetic gate, and it passes.** The three bands can sum to 100 (10 + 80 + 10), so this is not a repeat of the funnel split that could not sum to 100 caught on 2026-08-26. The low ends sum to 85 and the high ends to 105, which is normal for a range.
**Not banked, and worth stating so nobody banks it later.** "Our clients see an average decrease of 30% in their CPA when they're working with us" is a sales claim on his own agency with no baseline, window, account count or method. **It is promotional and it is not evidence.** The rest of the video is customer-research method (mining competitor reviews, Amazon reviews and Reddit for the buyer's own words) that restates what this file already holds.
Sources: Fraser Cottrell, FREE Meta Ads Course for Shopify Dropshipping, 2026-08-30
Last touched: 2026-08-31
"""

CLAIMS["Attribution & Incrementality.md"] = """
### AT-111 \u00b7 Every one of the five CRO tests that published a sample size is UNDERPOWERED for the lift it reports, by 1.6x to 7.6x, and the same recomputation validates AT-027's own threshold
Tier: T2 \u00b7 Status: active
This codex has been asking since 2026-08-27 for a landing-page or page-test source that states a denominator. [[Attribution & Incrementality#AT-106|AT-106]] closed that gap with a negative: nobody on the roster states a sample size, a conversion floor or a confidence level. **A source has now published denominators, five of them, and the answer is worse than no methodology. The methodology is stated and the tests do not clear it.**
**The recomputation.** For each test at [[Creative Science#CR-210|CR-210]], the per-arm sample needed to detect the reported relative lift at that test's own observed conversion rate, two-sided 5%, 80% power, standard two-proportion sizing:

| Test | Visitors | Orders | Observed CR | Reported lift | Per arm actual | Per arm needed | Short by |
|---|---|---|---|---|---|---|---|
| Bestseller badge | 140,000 | 3,500 | 2.50% | +6.0% | 70,000 | 170,059 | 2.43x |
| Font size | 57,000 | 1,600 | 2.81% | +5.0% | 28,500 | 217,414 | 7.63x |
| Shipping price | 250,000 | 6,600 | 2.64% | +3.3% | 83,333 | 531,602 | 6.38x |
| Savings % in button | 72,000 | 1,300 | 1.81% | +8.5% | 36,000 | 118,161 | 3.28x |
| Product title | 49,000 | 1,900 | 3.88% | +10.0% | 24,500 | 38,914 | 1.59x |

**Five out of five fall short. The best of them, the product title test, has 63% of the sample its own result needs. The worst, the font size test, has 13%.** The shipping price test is worse than the table shows, because it ran at least three cells rather than two, which is how 250,000 visitors, the largest sample in the set, ends up with the second-worst shortfall.
**The counter-intuitive part, and it is the useful part.** **A big sample does not rescue a small effect.** Required sample scales with the inverse square of the effect, so the 3.3% shipping lift needs roughly nine times the sample of the 10% title lift at the same conversion rate. **The tests reporting the most impressive-sounding traffic are the ones reporting the smallest effects, and those are exactly the ones that need the most traffic.** Reading down a list of test results and trusting the ones with big visitor counts gets this backwards.
**AT-027 was checked against its own arithmetic and it holds.** [[Attribution & Incrementality#AT-027|AT-027]] says trusting a 10 to 20% conversion lift needs about 1,000 conversions per variant, about 40,000 sessions per variant at a 2.5% conversion rate. Recomputed: 40,000 sessions per arm at 2.5% detects a **12.5%** relative lift (39,182 sessions, 980 conversions), which sits squarely inside its stated 10 to 20% band. **AT-027's numbers are sound and it is now the load-bearing claim in this section.** The full curve at 2.5%, per arm: 6% needs 170,059 sessions, 8% needs 95,658, 10% needs 61,221, 15% needs 27,209, 20% needs 15,305.
**What this does and does not say.** It does **not** say the seven changes are worthless or that the lifts are fabricated. Every one of the five reports internally coherent numbers (see CR-210) and the changes are cheap and directionally sensible. **It says the specific percentages must never be forecast from, never quoted to a client as an expected lift, and never used to rank one change against another.** A +6% and a +5% from these samples are indistinguishable from each other and from zero.
**The escalation that compounds it.** The same operator advises that when a test fails you try another increment and keep going. Repeated looks at underpowered arms until one crosses is the classic false-positive machine, and it is the same failure AT-027 already names as daily peeking with early stopping.
**Consequence for our own book, and it is a hard one.** Our accounts are lead generation into Meta Instant Forms. At the traffic our clients buy, **we cannot run a page test that would detect a single-digit conversion lift, and neither can most of the brands publishing these results.** The honest options are unchanged: ship the cheap sensible change without claiming a measured lift, or test only changes large enough to show up at our volume.
Sources: Andrew Faris with Dave Diederen (Centra Labs), 7 Real CRO Tests That Drove Big Profit Lifts, 2026-08-31; recomputation performed 2026-08-31 against the samples stated on screen
Last touched: 2026-08-31

### AT-112 \u00b7 A THIRD independent attributed-versus-incremental gap, an attributed 20 to 30 return reading 5.6 incremental, and the one case-study reporting practice in this corpus worth copying
Tier: T3 \u00b7 Status: active
Blue Sense Digital, 2025-04-22, on a nine-figure Australian fashion brand's Spain launch. **Attributed return on ad spend read "a 20. It was a 30 even". Incremental return on investment read 5.6.** That is a gap of **3.6x to 5.4x** between what the platform claimed and what the launch was measured to have caused.
**Why the third sighting matters more than the first two.** [[Attribution & Incrementality#AT-098|AT-098]] holds a 13 attributed return reading 5 once split to new audiences and 1.71 on incremental attribution, and the same family holds Meta's own incremental column cutting 108 purchases to 29 on one campaign. **Three independent accounts, three different brands, three different measurement routes, and the gap lands between roughly 3.5x and 5.5x every time.** That is now a stable enough range to plan against rather than a set of anecdotes.
**His stated reason for the gap in this case is the one that applies to most of our clients' better numbers:** the brand already had stores in Spain, existing organic revenue and brand awareness, so "when you launch onto the platforms, you're immediately going to have a ton of over-attribution just due to the fact of the existing brand presence."
**The reporting practice, and it is genuinely good.** He reports the case study as a **change in year-on-year growth RATE**, not as a growth number, and says out loud why: "no one's going to put numbers together based on the difference in year-on-year growth rates. And that's what we've done this whole time. I haven't said that we grew the account 600% year on year. I've said that they were growing 200% and we took that to 600%." **A brand already compounding hard will make any agency look good on a raw year-on-year figure. Reporting the delta in the growth rate strips out the trend the client already had.** That is the honest version of a case study and it is worth copying into how we present our own results.
**How it was measured**, which is more than most sources supply: an in-platform Meta geo lift experiment in the US, a manual correlation geo lift on one selected US state read against the rest of the US cohort on new-customer lift, and in-platform geo lift in Australia as well, which he notes is harder there because Australia has few homogeneous states to pair.
**\u26a0 Arithmetic gate, and this file's usual source fails it twice.** "We doubled year-on-year growth rate from 119% to 362%" and, one sentence later, "we almost 3xed it". **362/119 = 3.04. It is a tripling. "Doubled" is wrong and he corrects himself without noticing.** Second: Facebook Australia growth of 400% in January and 250% in February is given as "an average of 0% year-on-year growth up to 327%". **The average of 400 and 250 is 325, not 327.** Third, softer: the video's headline says US sales grew "over 650%" while the body figure is a **645% increase in new customers**, which is both rounded up and a different metric. **This is the channel carrying the source-reliability warning at [[Marketing Math & Unit Economics#MM-176|MM-176]]. The 5.6 incremental figure and the 20-to-30 attributed range are the load-bearing numbers here and they are internally consistent; the growth-rate headlines are not, and must be recomputed before any of them is repeated.**
**One absolute claim recorded with its emptiness attached.** On spending against existing-customer lists he says: "We have run so many incrementality tests internally where we have taken existing customer lists, spent more on them, and measured whether there were any incremental conversions... There was zero. I'd never seen it work." **No test count, no spend, no brands, no dates, no data shown.** It is the mechanism people reach for under [[Meta Delivery & Andromeda#MD-019|MD-019]]'s under-10% threshold, and it is an assertion, not the evidence for it.
Sources: Blue Sense Digital, How We Accelerated KOOKA\u00cf Australia's Growth Rate By 100%, 2025-04-22 (backlog, read in full 2026-08-31)
Last touched: 2026-08-31
"""

CLAIMS["Scaling Models.md"] = """
### SC-153 \u00b7 The post-ID harvest fails on exactly the multi-headline, multi-text ads that SC-022's whole architecture is built out of
Tier: T3 \u00b7 Status: active
A small operational limit with a large structural consequence, found in a four-minute tutorial in the backlog.
Blue Sense Digital, 2025-04-18, walking the post-ID pull. The method is the one this file already prescribes: open the ad, Share, "Facebook post with comments", copy the post ID out of the URL, then in a new ad choose "Use existing post" and paste it. A dev-tools fallback exists when the URL does not expose it: inspect the post, search the source for the post ID.
**The limit, stated in passing and never followed up:** "sometimes if you have multiple headlines and multiple primary texts, sometimes the post ID process doesn't work... it is a bit of a gray area. Sometimes it works, sometimes it doesn't."
**Why that is not a footnote.** [[Scaling Models#SC-022|SC-022]] builds the control ad set out of harvested unicorn post IDs, and [[Scaling Models#SC-023|SC-023]] specifies harvesting them from a 3-2-2 flexible ad, which is **by construction an ad carrying multiple headlines and multiple primary texts**. If the pull is unreliable on exactly that object, then the harvest step in the architecture has a failure mode nobody in this file has priced. **Nobody has checked whether the flexible-ad case is the same case he is describing, and it should be checked on one of our own accounts before the architecture is recommended again.**
**The reason to bother harvesting at all, restated by him and consistent with the rest of this file:** the post ID carries the accumulated likes and comments, and "if you change anything on that ad or recreate a new ad, you lose all of that social proofing."
**Tier guard.** One operator, in passing, with no example of a failure shown and no frequency attached. It is a flag to verify, not a finding.
Sources: Blue Sense Digital, How to Find an Ads POST ID in Facebook Ads Manager, 2025-04-18 (backlog, read in full 2026-08-31)
Last touched: 2026-08-31
"""

CLAIMS["Marketing Math & Unit Economics.md"] = """
### MM-197 \u00b7 Do not open a second country below roughly $3M in the first one, and MER flatters an established market because it counts returning revenue the new market does not have
Tier: T3 \u00b7 Status: active
Blue Sense Digital, 2025-07-15, on more than 20 US launches for Australian e-commerce brands, built around one case study.
**The threshold, stated as a hard floor:** "do not launch in the US unless you're doing at bare minimum 3 mil in the Australian market." His reason is resourcing rather than demand: every launch splits the focus of the paid media team, the SEO team and the marketing manager, and doubles every KPI, so an under-resourced launch quietly taxes the market that got you there. On brands around $1M attempting it: "I never saw it work once."
**The same argument, applied to CHANNELS, is the half that matters for our book.** "If you're only spending 10K a month on Meta and you're thinking, well, I should probably get on to TikTok or Snapchat or Pinterest. The answer is you probably shouldn't... the key to growth is usually not diversification. It's focus and then you move into diversification." **Every client we run sits under $30k a month on one channel, so the focus half of this rule applies to all of them and the diversification half applies to none of them.** His stated ceiling before you need a second channel is very high and should be quoted with care given the arithmetic record of this channel at [[Marketing Math & Unit Economics#MM-176|MM-176]]; the principle stands regardless of where the ceiling actually sits.
**The MER argument, and it is the most useful thing in the video.** Marketing efficiency ratio includes returning-customer revenue. A mature market has hundreds of thousands of prior orders generating repeat purchases that get counted in the numerator while the new market starts from zero returning customers. **So the home market's MER is flattered by the trailing cohort and a new market's MER looks far worse than its actual performance, for reasons that have nothing to do with the advertising.** His estimate of the size of the distortion on the case brand: a stated MER of 4 is "probably closer to a three" once word of mouth and existing brand presence are removed. **Arithmetic check on the one convertible figure and it passes: a MER of 4 is a 25% marketing allocation, exactly as he states.** The prescribed fix is to set launch KPIs off gross margin and contribution margin two, including cost of delivery, taxes and tariffs, rather than off blended MER. That is the same instruction as [[Attribution & Incrementality#AT-038|AT-038]]'s acquisition MER, arrived at from the new-market side.
**The launch expectation ladder, which is directly reusable for client expectation setting:** month one is written off and will not be profitable, month two targets break-even, month three targets scale above a set revenue floor. The mechanical reason month one is dead is conversion lag, not failure: an average purchase window of about 10 days at home runs 12 to 14 days in a new market, so the first half of month one's spend correlates with almost no recorded sales. He also names the shape that follows: initial growth, then a plateau of two to three months while a bottleneck is found by trial, then a further unlock. **Setting the ladder in advance is what stopped the client pulling out of the market during the flat months, and that is the actual finding.**
**Two operational specifics worth keeping.** Localisation is not cosmetic: he claims a visitor who realises the goods ship from Australia converts at 50% lower or worse, and prescribes local-accent user-generated content, local rounded currency and a locally-plausible post-purchase experience. That 50% carries no data. And on geo: they launched a broad US campaign alongside a narrowed state-selected campaign, **the state-selected campaign significantly outperformed broad US**, and then hit diminishing returns as it scaled, at which point moving to country-wide targeting unlocked the next leg. **Sequence, not preference: narrow to find it, widen to scale it.** Described, never shown.
**\u26a0 The headline claim fails arithmetic.** The case brand is given as "about a 2 to 3 million Australian business", month one US revenue of $20 to $25,000, month six US revenue of $173,000. He then says "the US business within a six-month period became a $2 million business... And this was a $3 million business at the time. So we effectively doubled this business." **$173,000 a month annualises to $2.08M, which is a RUN RATE off a single month and not realised revenue. And $3M plus $2M is $5M, which is a 67% increase, not a doubling. Doubling a $3M business needs $3M of new revenue, and the stated increment is $2M.** He also takes the top of his own "2 to 3 million" range for the base and does not state whether the Australian and US figures are the same currency. **The trajectory is real and impressive at 7.7x from month one to month six on the midpoint. The word "doubled" is not, and must not be repeated.**
Sources: Blue Sense Digital, The 3 Pillars to A Successful US Launch, 2025-07-15 (backlog, read in full 2026-08-31)
Last touched: 2026-08-31
"""

for fname, text in CLAIMS.items():
    p = S / fname
    body = p.read_text(encoding="utf-8")
    if not body.endswith("\n"):
        body += "\n"
    p.write_text(body + text.lstrip("\n"), encoding="utf-8")
    print(f"appended to {fname}: {len(text.splitlines())} lines")
