# -*- coding: utf-8 -*-
"""2026-08-23 backlog merge: 25 transcripts, 7 extraction agents."""
import sys
sys.path.insert(0, r"E:\claude code marketing skill\.claude\skills\advertising-science\lib")
from merge_helper import amend, mint, audit

SC = "Scaling Models.md"
CR = "Creative Science.md"
MD = "Meta Delivery & Andromeda.md"
LS = "Learning & Signal.md"
AU = "Auction Mechanics & Bidding.md"

CT_MAY = "Professor Charley T, The BEST NEW Way to Scale Facebook Ads, 2026-05-17"
CT_FEB4 = "Professor Charley T, The NEW BEST Way to Scale Meta Ads for 2026, 2026-02-04"
CT_FEB17 = "Professor Charley T, Copy This NEW Facebook Ads Creative Strategy, 2026-02-17"
CT_MAR = "Professor Charley T, How He Scaled Facebook Ads to 15k/Day in 5 months, 2026-03-24"
BH_RET = "Ben Heath, Facebook Ads Retargeting Has Completely Changed, 2026-03-17"
BH_TGT = "Ben Heath, Facebook Ads Targeting Just Changed Here's What It Means, 2026-03-27"
BH_VR = "Ben Heath, I Found A BETTER Way To Do Meta Ads Targeting in 2026, 2026-05-05"
BH_LL = "Ben Heath, Facebook Ads in Learning Limited Here's The Fix, 2026-03-31"
SP_ALL = "Sam Piliero, Everything You Need to Know About Facebook Ads in 2026, 2026-03-12"
SP_ALGO = "Sam Piliero, The Entire Facebook Ads Algorithm Explained in 5 Minutes, 2026-06-15"
FC_DIV = "Fraser Cottrell, Creative Diversity Post Andromeda, 2026-05-10"
FC_WIN = "Fraser Cottrell, How to Make Winning Meta Ad Creatives, 2026-05-30"
MS_ABO = "Dr. Matt Shiver, The Truth About ABO vs CBO Facebook Ads, 2026-05-26"
MS_QL = "Dr. Matt Shiver, How to Train Facebook to Bring You Qualified Leads, 2026-05-19"
MS_DBL = "Dr. Matt Shiver, The Fastest Way to Double Your Leads, 2026-03-31"
NT_STR = "Nick Theriot, Best Facebook Ads Campaign Structure To Scale In 2026, 2026-08-21"
NT_PROD = "Nick Theriot, My Most Successful Products That Scale With Facebook Ads, 2026-07-08"
BS_ABO = "Blue Sense Digital, ABO vs CBO Which One You Should Use, 2026-01-26"
BS_STAT = "Blue Sense Digital, How To Make Better Meta Ads 8 Static Creatives Analysed, 2026-03-12"
BS_LP = "Blue Sense Digital, Stuck In The Learning Phase Here's Why Your Meta Ads Still Won't Scale, 2025-12-17"

print("== AMENDMENTS ==")

amend(SC, "SC-008", """
**CORRECTION 2026-08-23, and it shrinks this disagreement more than anything else on file. Charley T does not say kill the budget hog. He says kill the WORST-PROFIT ad among the top spenders, and he caps the daily cull.** Read in full his instruction is "Look at the ads spending the most money, and identify the ones making you the least profit per sale. That's where the immediate leverage is", and in the scale-down section "find the ones with the worst CPT and turn them off. Let the budget reallocate to your strongest performers and give this system a chance to fix itself before you touch spend. Nine times out of 10, the problem isn't the budget, it's how Andromeda decided to use it." He also supplies a brake nobody else in this contest has, recorded separately at [[Scaling Models#SC-132|SC-132]]: never turn off more than 20% of spend in a day, because pausing an ad is itself a budget change. So the position we recorded as "kill the high spender" is really "kill the high-spend, LOW-GROSS-PROFIT ad, at a maximum of 20% of account spend per day."
**Nobody in this contest defends killing a PROFITABLE high spender.** The four leave-on voices are defending profitable top spenders and Charley T is cutting unprofitable ones, so the apparent 4-to-1 split was substantially a disagreement about which ad was being described. What genuinely survives is narrower and still open: whether an unprofitable-LOOKING top spender is actually unprofitable, or is a top-of-funnel engine whose value lands on other ads. Zero controlled data on either side, unchanged. This also reconciles cleanly with SC-050 at law 12, where the ads cut were funded AND at negative profit per transaction.
**One line on the other side, and it is weaker than it looks.** Blue Sense, walking an ABO diagram, says of the low-spend ad sets "You might even decide to turn them off", which reads against the anti-kill position this codex credits to him. Two caveats before treating it as a reversal: it concerns AD SETS in an ABO campaign, whereas his recorded "Don't do that" concerns starved ADS inside an ad set, and both of his stated mechanisms (assist role in the conversion sequence, reserve bench at fatigue) are ad-level. It is also a throwaway half-sentence inside a diagram walkthrough. Log it, do not score it.
""", [CT_MAY, BS_ABO])

amend(SC, "SC-001", """
**2026-08-23 added four more operators and, more usefully, the first explanation of why the range is so wide.**
**Charley T publishes THREE named methods rather than one number** (2026-05-17), and they sit at the bottom of the field's band. Linear, add a flat $10 to $50 a day. Fractional, "instead of adding $10 every day, you might increase by 2% daily", with the claim you "could 6x your daily budget in 90 days" (1.02^90 = 5.94, so the arithmetic is sound and is arithmetic, not evidence). Marginal, the one he actually operates: "If my CPA over the last 7 days is below my target, increase the budget by small percentage, but never by more than the profit margin allows. So, for instance, if my target CPA is 50 bucks, I'm currently coming in at a 45, I can scale by 5%, and if I get no additional sales, I'm still profitable." That independently re-confirms, at a second date, the 5%-with-a-7-day-lookback figure this claim already credits to him. He is also the only operator on file with a SCALE-DOWN protocol and a HOLD: "Scale down at half the speed you scale up... and then you wait. Don't touch anything for at least 48 to 72 hours. Let the spend redistribute."
**Sam Piliero contradicts his own banked band outright.** This claim records him at 5-10 / 20-30 / 50%+ by headroom, and a separate transcript has him at "10% to 30%". On 2026-03-12 he says: "for many businesses that we work with, doubling spend is common practice. We don't worry about increasing by 10 or 12 or 15%." That is a third incompatible prescription from one operator, and it explicitly rejects the 10-15% band he is elsewhere recorded inside. **His step-size testimony is no longer usable as a point estimate. Quote him only as a range with the date attached.**
**Matt Shiver: 20% every 2 to 3 days**, applied at ad-set level on a $250/day base, with one new $250/day ad set launched weekly alongside.
**Nick Theriot re-confirms 20% per day gated on CPA, and supplies the budget LEVEL this claim has been missing for everyone except Heath.** On a screen-shared account at $5,000/day: "for this account, I think it's anything under 50, we can just keep bumping up that budget by 20% a day." So the 20% stays percentage-based all the way to $5k/day rather than switching to absolute steps at scale, which is the opposite of Heath's decreasing-function model at SC-100. **Two operators, directly opposed on whether step size shrinks as budget grows, neither with a test.**
""", [CT_MAY, SP_ALL, MS_ABO, NT_STR])

amend(CR, "CR-154", """
**2026-08-23. The vocabulary half of this dispute is now essentially closed, and one operator's number turns out not to be a smaller number at all.**
**Charley T's structure, stated plainly (2026-02-17): five ad objects per ad set, each a 3x2x2.** "Five rings all connected... And each ring can be built as a 322. That means three creatives, two primary texts, and two headlines... So while it looks like one ad in the account, inside are multiple combinations." Three of the five rings are prospecting and two are retargeting. **That is about 60 creative combinations live, from five ad objects.** Set against Ben Heath's 20-plus, he is not running fewer creative variants. He is running fewer AD OBJECTS with the variation pushed inside the ad unit. The disagreement is about WHERE THE SPLIT HAPPENS, not about creative volume, which is the same trap this claim already flags when it notes his unit "silently shifts from discrete ads to 322 flex units". His launch rates, both explicitly launched-not-live: 10 ads in 30 days, and "We've launched five ads in the last 6 weeks and two of them are losers."
**Matt Shiver, unit pinned to live-concurrent and the budget corrected.** "I'm going to put $100 a day minimum, typically, for optimizing for these leads and I'll put five to 10 ads inside of there." That is 5 to 10 LIVE-CONCURRENT inside one ABO ad set at a $100/day floor. Corrections to what this codex previously carried for him: the $200/day figure and the "one offer each" framing do not appear, and the anti-pattern line about ten ad sets at $5 each is not in these transcripts and should not be sourced to them. He separately runs 20 to 50 ads in a single CBO ad set for pure volume, and 3 to 5 ad versions per ad set as a WEEKLY LAUNCH unit, so both units genuinely coexist in his vocabulary.
**Blue Sense supplies a live-concurrent number and then disowns precision.** "We generally aim for three to six, sometimes up to 10 ads in an ad set. Um, I wouldn't recommend running one. Probably wouldn't recommend running a 100." His own summary is the honest one and belongs in any answer we give: **"transparently nobody knows what the actual right amount is."**
**Nick Theriot, after SEVEN transcripts, still states no live concurrent count.** Every figure remains a launch rate (1 ad idea per day per client, 5 per week), a composition ratio (3 creatives per idea), or an account topology (campaigns = countries x product categories). The nearest miss is hedged and illustrative: "at any given time we could have 10 ad sets with all problem aware each one." **New and better than the revenue ladder: he states the launch rate is set by HEADCOUNT, not by budget or account size.** "every week we just keep launching five ad sets. That's just cuz what my creative strategists are paid to do." One strategist at one idea per working day yields five a week, which predicts the 10-20 and 20-40 tiers are simply headcount multiples and explains why he refuses to index ad count to daily budget: budget does not employ the strategist. He also never mentions switching ads off between launches in either transcript, so the climbing-live-count finding survives intact.
**Ben Heath gives NO live count in four transcripts read this pass.** The only ad-count figure is "the five new ad creative that we produced at the end of the week", a batching example, launched per week. Do not read it as a concurrency ceiling.
""", [CT_FEB17, CT_FEB4, MS_ABO, BS_ABO, NT_STR, NT_PROD, BH_LL])

amend(MD, "MD-013", """
**2026-08-23. The strongest UI reading yet, and the operator contradicts himself ten days later.** Ben Heath walks the ad set audience panel and names Meta's two sections out loud: "in audience, we've got controls, so those are hard boundaries, hard constraints, Meta won't go outside that targeting. It's basically just location and a few other things, but then we've got within the suggestion audience, we've got um show settings, we've got include these custom audiences... because it's within this suggestion audience section, it gives Meta full flexibility." He then demonstrates the hardening path end to end, naming BOTH switches: "it depends whether or not you've got this option here, further limit the reach of your ads... If you click on that and then you go ahead and click switch setup, Meta's going to come up with all sorts of warnings to try and convince you not to do this", and "you also, very important, want to make sure that you don't have use as suggestion ticked. If you do, then it's just going to function as the previous setup... but if you have that unselected, use as suggestion, add in your warm audiences here, and then Meta is going to put ads in front of these people and these people only." He states availability is partial ("Not everyone has this") and caveats accuracy himself: "Targeting is never 100% accurate."
**The contradiction, and it is inside one operator across ten days.** On 2026-03-27 he says detailed targeting options "are always going to be added in as suggestions, meaning that Meta can choose to target people who do fit into that detailed targeting category... or not". The word "always" is wrong as stated, because he demonstrated the exception himself on 2026-03-17. The two reconcile only through the partial rollout. **Practical consequence unchanged and reinforced: check the account for the toggle before attributing non-binding behaviour to Andromeda, and never quote a blanket "always a suggestion" claim without checking which account and which date it came from.**
""", [BH_RET, BH_TGT])

amend(MD, "MD-003", """
**2026-08-23. Fraser Cottrell restates the collapse in its strongest form yet and shows nothing, which leaves the central evidentiary hole exactly where it was.** His mechanism claim: "Every single ad in your ad account is labeled with a similarity score. This is behind the scenes in Meta, but essentially it looks at all your ads and goes, 'That one's very similar to that one.' and then treats them as the same asset." He cites no source and is not a Meta employee, so tier the mechanism T4 even though the practice around it is T3.
**His entire evidence is eyeballing two ad-account thumbnail grids**, one he predicts will fail and one he approves of, with no performance figure attached to either. **He concedes on camera that the supposedly collapsed account is currently working**: "They might be seeing results from this, but it's only a matter of time until they don't anymore." That is the unfalsifiable form of the claim and it should be recorded as such. **Still nobody on either side of this law has shown an entity ID or a unique-reach figure.**
**One substantive difference from how this claim is written: his unit of diversity is FORMAT and audience segment, not angle x offer x persona.** He builds diversity as "A UGC video which is targeted at a specific segment... A podcast style... A founder-led piece", which is a weaker standard than concept-level. He never addresses whether a format change escapes a collapse, and never addresses hook-level near-duplicates in this context, which is notable because he ships four hook variants of one body in a transcript from twenty days later.
""", [FC_DIV])

amend(LS, "LS-001", """
**2026-08-23. Two operators supply the practitioner override, and it says the 50 is soft in both directions.**
**Ben Heath states Meta's number and then contradicts it from his own book.** He relays the threshold as "50 results per week" of whatever the ad set optimises for. Then: "in practice, I've seen many ad sets properly exit the learning phase and not end up in learning limited, even if they're generating fewer results than 50 per week. There doesn't seem to be an absolute number where it will or won't... Sometimes it might be if you generate 20 results per week... Sometimes it might be more like 40. And I don't think I've ever seen an example where a campaign or an ad set has been running more than 50 results per week and has ended up in learning limited." He also gives the only learning-phase DURATION on file, "say 24 to 48 hours on average", and reports ad sets exiting into active with no increase in weekly conversions at all, attributing it to stability rather than volume. Note he supplies **no resettle duration after a budget change** anywhere in four transcripts.
**Blue Sense goes further and says most accounts never exit, which is the state our own book lives in permanently.** "for 90% of ad accounts, what do you do to be able to exit the learning phase and get at least 50 purchase events a week? The answer is you don't." And the argument that the threshold cannot be a hard gate: "if you had high average order value or high ticket businesses, they would just never be able to exit the learning phase. If you're selling something for $10,000 and you're a SMB business, you're just never going to exit... How does Meta ever learn? Can you even use Meta as an advertising platform? And yes, because there is this cascading effect." His mechanism for what happens instead is banked separately at [[Learning & Signal#LS-063|LS-063]] and is T3 assertion, NOT documentation. His credential is spoken and unshown: sub-50 ad sets scaled profitably across "tens of millions" in spend.
**Honest scope note: neither operator confirms or contradicts the significant-edit reset half of this claim. Blue Sense never mentions resets at all across three transcripts, treating learning purely as a volume state.**
""", [BH_LL, BS_LP])

print()
print("== MINTS ==")

mint(MD, "MD-116", "A cold-configured campaign spent about 40% of $80,000 on warm audiences and took more than half its purchases there",
     "T2", "active", """
Ben Heath opens the Audience Segments breakdown on a live client campaign and reads the split: "this campaign has spent $80,000 just under, um 47,000, 48,000 of which have been spent on genuinely new audience. So, what's that coming in at? 40% almost being spent on a combination of engaged and existing customers." And on the outcome side: "out of the 942 purchase generated, more than half have come from engaged audience and existing customers." The cost per purchase on the warm segments is visibly lower, though no figure is spoken.
Figures on screen, account unnamed. This is the first shown measurement in the codex of how far a nominally cold ad set drifts warm, and it is the practical consequence of [[Meta Delivery & Andromeda#MD-013|MD-013]]: if custom audiences are suggestions, warm-configured and cold-configured ad sets converge on the same people. Heath's own framing of the structural consequence: "we run many campaigns, many examples where we've got what we think is a warm audience campaign, what we think is a cold audience campaign or ad sets... and they just end up targeting the same people."
Operating consequence for our accounts: the instrument is free and none of our clients have been read this way. It pairs directly with the never-opened attribution comparison at AT-082. A local clinic or dealer whose "cold prospecting" campaign is 40% warm is buying its own existing patients at cold-acquisition CPMs.
Precondition worth recording because it silently voids the report: Audience Segments must be defined first under Advertising Settings, otherwise the breakdown reads "all unknown". Heath configures it on screen on a second account.
""", [BH_RET])

mint(MD, "MD-117", "Meta's creative testing tool guarantees test ads a spend FLOOR, not an equal split, and delivery still tilts to the winner",
     "T2", "active", """
Matt Shiver sets the tool up on screen and then shows what actually happened in the account. The intended split was even. The observed split was not: "what essentially happened was two of the ads got $30 a day in spend and one of them got $50 a day in spend because Facebook found that that $50 a day one was better, so it gave it more spend." He states the semantics correctly as a floor: "you're guaranteeing that the two test ads that you drop in here are going to get $20 of the $30 in spend. If one of them performs really well, there is a chance that this one ad that's already in there may only get $5 a day, maybe $10 a day in spend."
So the guarantee protects the TEST ads and can starve the INCUMBENT, and the even-delivery promise degrades as soon as one variant wins. **A creative test left running past the point where a winner emerges is no longer a clean test**, which matters because the tool's own duration field invites 7 to 14 days.
Meta's on-screen warning string, read aloud: "if your campaign only includes test ads, they may receive more of the campaign budget."
Related and unresolved: Sam Piliero rejects the tool on exactly this feature, arguing guaranteed delivery is the wrong thing to want, "It's going to allow you to compare five different versions of your creative in a test that ensures delivery to new test ads. We do not want insured delivery. This is a negative, not a positive." Shiver argues the opposite, that same-ad-set serving is what makes the comparison valid. Both are asserting. The 2-to-5 ad cap in the tool is a UI cap on a split test and is not an ad-count recommendation, per the trap already recorded at CR-154.
""", [MS_DBL, "Sam Piliero, I Found a BETTER Way to Test Facebook Ad Creatives, 2026-03-09"])

mint(MD, "MD-118", "Illustrating a health condition rather than photographing it may dodge a CPM penalty and delivery throttling",
     "T3", "active", """
Blue Sense, analysing a hair-loss static that uses a cartoon rather than a photograph: "Doing this with an actual image would be pretty hard, and it would probably be a little bit graphic in terms of someone actually having hair loss, and it might trigger the platform to either crank CPMs up on it or not push that ad as hard because it's leaning into health conditions."
Practitioner assertion about a delivery behaviour, hedged twice by the speaker ("probably", "might"), with no CPM figures and no matched pair. Tiered T3 and explicitly not promoted, because it is exactly the kind of mechanism claim the codex has been burned by before.
**Recorded because it is the cheapest high-value test on our own board.** Every chiropractic account we run advertises a pain condition, our chiro law says the hook is the BODY PART, and we ship literal pain imagery routinely. A matched pair on ChiroWorks or Mattia, literal pain photo against illustrated anatomy with the headline held constant, reading CPM and not CPL, would convert this into our own T2 in a fortnight. It also sits adjacent to the Meta health-policy rewrite of July 2026 on personal attributes, which governs what the COPY may assert and says nothing about imagery, so this is a separate question and not a restatement of that rule.
""", [BS_STAT])

mint(LS, "LS-063", "When an ad set cannot reach 50 conversions a week, Meta is claimed to cascade UPSTREAM to the nearest event with volume: purchases, then clicks, then impressions",
     "T3", "active", """
Blue Sense's model for what happens below the threshold at [[Learning & Signal#LS-001|LS-001]], and it is the mechanistic answer to the permanent-limited-learning state our entire book sits in. "Instead, what Meta does is it goes up the funnel and it looks for the closest thing to 50 conversions a week, whether that's clicks, whether that's impressions, etc. This doesn't qualify. You don't have 50 purchases. So, it goes upfunnel and it looks at clicks. In this instance, you're not getting 50. You're only getting 45. Not good enough... It moves further up the funnel and it looks at impressions."
**TIER GUARD, and it is load-bearing. This is NOT documentation.** He opens by declaring the common understanding wrong and then substitutes his own model. No Meta page is shown, no product copy is quoted, no delivery column is opened, and the 13-purchases / 45-clicks figures are whiteboard illustrations. The extension of the same "50" to the click and impression tiers is his own invention with nothing behind it. Do not let this claim borrow authority from the T1 threshold it sits under.
**The consequence he draws is the useful part, and it is testable.** In the impression-fallback state, ad-level CPM becomes the primary allocation signal: "A very large indicator of where Meta distributes ads early on during a new campaign or a new ad set is actually the CPMs at an ad level." Since video CPMs run systematically above image CPMs, mixing formats inside one sub-threshold ad set means spend pools into the cheap format and the expensive one never gets read. His rule: "all of your spend generally ends up pooling into images when you go and combine multiple different mediums into one adset. So you want to be thinking through how you can structure your mediums into different adsets so that this doesn't occur. Your video will never get tested which is probably your highest investment content type."
**This transfers to our book without translation and contradicts nothing we hold.** Every client we run is below the threshold permanently, and we routinely put statics and video in the same ad set. He states the same cascade operates at the CBO level, which is his explanation for why a high-CTR low-ROAS ad set can take an entire campaign budget.
""", [BS_LP, BS_ABO])

mint(LS, "LS-064", "Shiver picks ABO or CBO off the DAILY EVENT RATE, not the budget, and hands allocation to Meta only between 2 and 10 events a day",
     "T3", "active", """
A decision tree keyed to conversion volume rather than spend. Leads, DMs or low-ticket meant to ascend: ABO, $100/day minimum, 5 to 10 ads in the ad set. Schedules at 0 to 1 events/day: ABO, $150 to $250/day, with active CPL monitoring and a kill rule. Schedules at 2 to 10 events/day, roughly $500 to $1,000/day: CBO, because "now we actually have enough pixel fires for the machine to learn". Schedules at 10+/day: back to ABO, three ad sets at $250/day, for account-risk diversification against single-winner concentration. Purchases or pure list build: CBO.
His mechanism for refusing CBO in high-ticket lead gen is the sharpest statement of it on file: "the lowest cost DM, the lowest cost lead, or the lowest cost lead magnet purchase does not mean that they're actually going to book calls, which is my main KPI in any type of high-ticket service." Plus a long-cycle structural argument: at 60 to 90 days to purchase, "how is Meta going to be able to optimize that funnel with a CBO?"
**2 to 10 events a day is 14 to 70 a week, so his practical floor for trusting Meta's allocation straddles the 50-per-week threshold without him ever naming it.** He never mentions the learning phase, the 50 figure, or custom conversions in this transcript.
**Caveat carried in his own words, and it should travel with every quotation of this tree: "I've changed my mind on this so many different times, and certain seasons one works better than another."** He also opens by demoting the whole topic: "if you have a good offer and good ads, and you're sending back the right pixel data for what you want to optimize for, that matters way more than anything I'm going to share with you in this video." Zero numbers appear on screen in the entire video. Record as a heuristic with a volatility flag, never as a law.
**Blue Sense lands on the same side from the opposite direction and adds the finding that kills the obvious compromise**, recorded at [[Scaling Models#SC-133|SC-133]]: high AOV or low conversion volume should lean ABO, because under-volume CBO allocates on CTR rather than revenue.
""", [MS_ABO, BS_ABO])

mint(SC, "SC-132", "Pausing an ad is a budget change, so never switch off more than 20% of account spend in one day",
     "T3", "active", """
Charley T's brake on his own culling instruction, and the only stated cap of its kind in the codex: "The easiest way to scale profits today without doing any extra work is simply to pause the worst performers first. Turning off ads is the same thing as changing the budget. So, never turn off more than 20% of the spend on any day."
The mechanism is the interesting half, because it makes a cull and a budget cut the same class of intervention, which would put both under the learning-reset rules at LS-002 and LS-003. Nobody has tested whether Meta treats a pause as a significant edit at ad level, so the mechanism is asserted, not established.
**Read this against SC-107, which reached the same conclusion from shown data by a different route:** kill risk scales with the SPEND SHARE removed rather than the ad count, priced off a real account where 95 ads were switched off at once and jointly held 10.89% of spend. Two independent arrivals at a spend-share framing, one from a stated rule and one from an account, still with no controlled test of the threshold itself. **The 20% is a round number with nothing behind it. Treat the framing as the finding, not the figure.**
Unit trap worth attaching: the same operator elsewhere prescribes pruning "about 10% at a time every week", which is a share of AD COUNT, not a share of spend. The two are roughly fourteen times apart if read loosely and he never reconciles them. Always state which denominator is meant.
""", [CT_MAY, CT_FEB17])

mint(SC, "SC-133", "CBO with ad-set minimum spend underperforms plain ABO, and the operator who reports it cannot explain why",
     "T3", "active", """
The obvious middle ground between CBO efficiency and ABO control is a CBO with minimum spend floors on the ad sets. Blue Sense reports it does not work and is unusually honest about not knowing the mechanism: "you can run a CBO with minimum ad spend limits on adsets... I've just found that doing that isn't incredibly successful. Um, strangely, ABOs perform better than a CBO adset with a minimum ad spend. I'm not sure why that's the case. I'm not sure if those adsets get deprioritized within the CBO and high intent audiences because Meta doesn't like them or exactly what the mechanics are there but it's just a worthy note."
No data shown, no account named, no comparison figures. Recorded because it closes off the fix most operators reach for first, and because it directly contradicts the structure Sam Piliero prescribes, which is a prospecting CBO with the ad-set minimum set to 1x CPA held for exactly 7 days then removed. **Two operators, opposite verdicts on the same mechanism, neither showing data.** Piliero's own framing is internally conflicted in the same video: he condemns forced spend ("Don't force creative testing... we are not smart compared to this algorithm") and then prescribes it ("we are now forcing spend to new tests... setting 7-day minimum budgets on all of our ad sets") about six minutes apart, and never argues the reconciliation.
Blue Sense's wider framing of the ABO/CBO choice is worth keeping alongside: the real question is risk against efficiency. CBO concentrates roughly "80% of your spend into 20% of your ads", which buys efficiency and buys concentration risk, and starves the new tests that would otherwise become the bench for when the winner fatigues. **He names no budget threshold anywhere, which is an absence worth recording, since the ABO/CBO question is usually posed as a budget cut point.**
""", [BS_ABO, "Sam Piliero, I Found a BETTER Way to Test Facebook Ad Creatives, 2026-03-09"])

mint(SC, "SC-134", "A 20%-per-day step is a permission ceiling, not a growth schedule: the account quoting it took a year to go 50x",
     "T3", "active", """
The cleanest correction available to how budget step-size rules get read, and it comes from inside the same transcript that states the rule. Nick Theriot screen-shares an account at roughly $5,000/day and says "for this account, I think it's anything under 50, we can just keep bumping up that budget by 20% a day." He also states its history: "We started off this campaign almost a year ago at $100 a day and just throughout the year I've been able to scale this up to currently right now at 5K a day."
**Those two facts are very far apart. Compounding 20% a day would take $100/day to $5,000/day in about 22 days. It took roughly 365.** So the realised average step is a small fraction of one percent per day, and the 20% is the maximum move permitted on a qualifying day, gated on cost per purchase clearing the target, on the days it clears.
**Operating consequence, and it applies to every percentage in [[Scaling Models#SC-001|SC-001]]: a step-size prescription is a ceiling per qualifying event, never a growth rate.** Anyone reading "20% a day" as a plan will model 50x in three weeks and be wrong by a factor of sixteen. This is the most likely source of the apparent 3%-to-100% spread in the field, because operators quoting a ceiling and operators quoting a realised cadence are answering different questions, exactly as happened with live-versus-launched ad counts at CR-154.
The $50 threshold is explicitly account-specific ("for this account"). The arithmetic here is ours, not his, and is offered as a reading correction rather than as a new measurement.
""", [NT_STR])

mint(CR, "CR-175", "Renaming the lead magnet, with the creative held identical, cut cost per lead 45% and lifted CTR 79%",
     "T2", "active", """
The cleanest shown creative result in the codex for lead gen, and the variable is genuinely isolated. Matt Shiver screen-shares a client account running one static under three different lead-magnet names, with the ad itself unchanged: "The ad is the exact same, no difference, just called it something different that's clearer."
Cost per lead: "Get the blueprint" $6.10, "Get a 10-page blueprint" $4.14, "Get a 10-page cheat sheet" $3.33. Cost per click: about $2.00, $1.42, $1.00. Click-through rate: 1.50%, 2.14%, 2.68%. All read off the account on screen.
The transferable mechanism is SPECIFICITY plus a FORMAT NOUN. Adding the page count moved it once; swapping "blueprint" for "cheat sheet", which promises less work, moved it again by a similar margin.
**Two honest limits.** Spend per variant was only $30 to $50 across 3 to 4 days, so this is directional rather than a powered test. And the landing pages were NOT matched to the names, which he separately says they should be, so part of the CPL gain is click-side and he never decomposes it. CPL fell 45% while CTR rose 79%, which is consistent with most of the movement happening before the form.
**Why it matters to our book: this is the cheapest test we are not running.** Every lead-gen client we operate has a named offer, and none of them has ever had the NAME tested against a matched control. It costs one duplicate ad and a weekend.
""", [MS_DBL])

mint(AU, "AU-076", "Value rules: up to 10 rules per set, bid up or down by percentage on age, gender, location, conversion location, device, OS or placement, and Meta warns cost per result may rise",
     "T1", "active", """
Full surface read off Ads Manager by Ben Heath, who builds a rule set live. Path is Advertising Settings then Value Rules. Capacity is stated in the UI: "You can see we've got rules, one out of 10. You can add up to 10 rules." Criteria enumerated from the dropdown: age, gender, location, conversion location (website against instant form), device (desktop against mobile), mobile operating system (iOS against Android), and placement. Two criteria can be combined inside one rule.
**Meta's own product copy, quoted aloud, and the acknowledgement is the part that matters:** "Reach your preferred audiences using value rules. Increase your bid on audiences that are worth more to your business", and the tickbox "I understand my overall cost per result may increase when using value rules." Meta also positions the feature as a consolidation play: "See better results with a single ad set."
**The trap, and it is easy to get wrong:** creating a rule set does nothing on its own. "Just because we've created it in here does not mean that it's applied to our campaigns. We still need to specifically say we want to use these in the ad sets."
T1 for the surface, the capacity and the product copy only, on the TT-029 and MD-099 precedent. **Nothing here says value rules perform**, and Meta's own copy concedes the opposite risk. The reason to hold this claim is that it is the mechanism underneath two live items: the reversible bid DECREASE at [[Auction Mechanics & Bidding#AU-019|AU-019]], which is the safe alternative to the gender exclusions that have burned us, and the unrun bid-multiplier route for lead quality at LS-050. Heath's own use case is a jewellery client whose male buyers bought gifts and never repeated, so the rule bid up on women. The 2.4x lifetime-value multiple he mentions sits inside an explicit hypothetical and is not a measurement.
""", [BH_VR])

print()
print("== AUDIT ==")
total, tiers, stat, per = audit()
print("claims:", total)
print("tiers:", tiers)
print("status:", stat)
for k, v in per.items():
    print(f"  {k}: {v}")
